### ISSUE TITLE
JobQueueGroup::singleton was deprecated in MediaWiki 1.37 and delete in 1.40

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#14]
Hello,

We are currently using mediawiki in 1.40 WMF3, until WMF2 JobQueueGroup::singleton was still supported but deprecated, this method is now removed and Webp does not work under 1.40.

Sincerely,

Kims

**Comment by octfx** [comment]
Thanks for the report, I'll try to have a look at it soon :)

**Comment by octfx** [comment]
Fixed in current develop

**Comment by GenerationFallout** [comment]
Hello,

The bug is still present when manually running ConvertImages.php in ssh :)


[f46b4834803c01af5b3f3f89] [no req]   Error: Call to undefined method JobQueueGroup::singleton()
Backtrace:
/fallout-wiki.com/httpdocs/extensions/WebP/maintenance/ConvertImages.php(93)
#0 fallout-wiki.com/httpdocs/maintenance/includes/MaintenanceRunner.php(309): ConvertImages->execute()
#1 fallout-wiki.com/httpdocs/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#2 fallout-wiki.com/httpdocs/extensions/WebP/maintenance/ConvertImages.php(136): require_once(string)
#3 {main}

**Comment by GenerationFallout** [comment]
As for me, I had not seen that the maintenance file has been renamed, everything works :)
